Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Initialize OGGM and set up the default run parameters
cfg.initialize(logging_level='WARNING')
rgi_version = '62'
cfg.PARAMS['border'] = 80

# Local working directory (where OGGM will write its output)
cfg.PATHS['working_dir'] = utils.gettempdir('oggm_gdirs_wd', reset=True)

# RGI glaciers: Hintereisferner and Kesselwandferner
rgi_ids = utils.get_rgi_glacier_entities(['RGI60-11.00897', 'RGI60-11.00787'])

# Go - get the pre-processed glacier directories
gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=3)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_1547/2748391699.py[0m in [0;36m<module>[0;34m[0m
[1;32m      8[0m [0;34m[0m[0m
[1;32m      9[0m [0;31m# RGI glaciers: Hintereisferner and Kesselwandferner[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m [0mrgi_ids[0m [0;34m=[0m [0mutils[0m[0;34m.[0m[0mget_rgi_glacier_entities[0m[0;34m([0m[0;34m[[0m[0;34m'RGI60-11.00897'[0m[0;34m,[0m [0;34m'RGI60-11.00787'[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m [0;34m[0m[0m
[1;32m     12[0m [0;31m# Go - get the pre-processed glacier directories[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/oggm/utils/_downloads.py[0m in [0;36mget_rgi_glacier_entities[0;34m(rgi_ids, version)[0m
[1;32m   1932[0m     [0mselection[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m   1933[0m     [0;32mfor[0m [0mreg[0m [0;32min[0m [0msorted[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0munique[0m[0;34m([0m[0mregions[0m[0;34m)[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1934[0;31m         [0msh[0m [0;34m=[0m [0mgpd[0m[0;34m.[0m[0mread_file[0m[0;34m([0m[0mget_rgi_region_file[0m[0;34m([0m[0mreg[0m[0;34m,[0m [0mversion[0m[0;34m=[0m[0mversion[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1935[0m         [0mselection[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0msh[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0msh[0m[0;34m.[0m[0mRGIId[0m[0;34m.[0m[0misin[0m[0;34m([0m[0mrgi_ids[0m[0;34m)[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1936[0m [0;34m[0m[0m

[0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/oggm/utils/_downloads.py[0m in [0;36mget_rgi_region_file[0;34m(region, version, reset)[0m
[1;32m   1903[0m     """
[1;32m   1904[0m [0;34m[0m[0m
[0;32m-> 1905[0;31m     [0mrgi_dir[0m [0;34m=[0m [0mget_rgi_dir[0m[0;34m([0m[0mversion[0m[0;34m=[0m[0mversion[0m[0;34m,[0m [0mreset[0m[0;34m=[0m[0mreset[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1906[0m     [0mf[0m [0;34m=[0m [0mlist[0m[0;34m([0m[0mglob[0m[0;34m.[0m[0mglob[0m[0;34m([0m[0mrgi_dir[0m [0;34m+[0m [0;34m"/*/{}_*.shp"[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mregion[0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1907[0m     [0;32massert[0m [0mlen[0m[0;34m([0m[0mf[0m[0;34m)[0m [0;34m==[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/oggm/utils/_downloads.py[0m in [0;36mget_rgi_dir[0;34m(version, reset)[0m
[1;32m   1828[0m [0;34m[0m[0m
[1;32m   1829[0m     [0;32mwith[0m [0mget_lock[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1830[0;31m         [0;32mreturn[0m [0m_get_rgi_dir_unlocked[0m[0;34m([0m[0mversion[0m[0;34m=[0m[0mversion[0m[0;34m,[0m [0mreset[0m[0;34m=[0m[0mreset[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1831[0m [0;34m[0m[0m
[1;32m   1832[0m [0;34m[0m[0m

[0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/site-packages/oggm/utils/_downloads.py[0m in [0;36m_get_rgi_dir_unlocked[0;34m(version, reset)[0m
[1;32m   1864[0m         [0mofile[0m [0;34m=[0m [0mfile_downloader[0m[0;34m([0m[0mdfile[0m[0;34m,[0m [0mreset[0m[0;34m=[0m[0mreset[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1865[0m         [0;31m# Extract root[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1866[0;31m         [0;32mwith[0m [0mzipfile[0m[0;34m.[0m[0mZipFile[0m[0;34m([0m[0mofile[0m[0;34m)[0m [0;32mas[0m [0mzf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1867[0m             [0mzf[0m[0;34m.[0m[0mextractall[0m[0;34m([0m[0mrgi_dir[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1868[0m         [0;31m# Extract subdirs[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/zipfile.py[0m in [0;36m__init__[0;34m(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)[0m
[1;32m   1255[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1256[0m             [0;32mif[0m [0mmode[0m [0;34m==[0m [0;34m'r'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1257[0;31m                 [0mself[0m[0;34m.[0m[0m_RealGetContents[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1258[0m             [0;32melif[0m [0mmode[0m [0;32min[0m [0;34m([0m[0;34m'w'[0m[0;34m,[0m [0;34m'x'[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1259[0m                 [0;31m# set the modified flag so central directory gets written[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/zipfile.py[0m in [0;36m_RealGetContents[0;34m(self)[0m
[1;32m   1318[0m         [0mfp[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mfp[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1319[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1320[0;31m             [0mendrec[0m [0;34m=[0m [0m_EndRecData[0m[0;34m([0m[0mfp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1321[0m         [0;32mexcept[0m [0mOSError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1322[0m             [0;32mraise[0m [0mBadZipFile[0m[0;34m([0m[0;34m"File is not a zip file"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/pyenv/versions/3.9.8/lib/python3.9/zipfile.py[0m in [0;36m_EndRecData[0;34m(fpin)[0m
[1;32m    261[0m [0;34m[0m[0m
[1;32m    262[0m     [0;31m# Determine file size[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 263[0;31m     [0mfpin[0m[0;34m.[0m[0mseek[0m[0;34m([0m[0;36m0[0m[0;34m,[0m [0;36m2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    264[0m     [0mfilesize[0m [0;34m=[0m [0mfpin[0m[0;34m.[0m[0mtell[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    265[0m [0;34m[0m[0m

[0;31mAttributeError[0m: 'NoneType' object has no attribute 'seek'
AttributeError: 'NoneType' object has no attribute 'seek'

